{% set name = "pyvinecopulib" %}
{% set version = "0.6.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyvinecopulib-{{ version }}.tar.gz
  sha256: 7dcf9ba9de78a38ab0ba2f77d4b2a2835567af923bfa8ae9f75eb3e63375bdd3

build:
  skip: True  # [py<38]
  script_env:
    - Boost_INCLUDE_DIR={{ environ['PREFIX'] }}/include  # [unix]
    - EIGEN3_INCLUDE_DIR={{ environ['PREFIX'] }}/include/eigen3  # [unix]
    - Boost_INCLUDE_DIR={{ environ['PREFIX'] }}\\Library\\include  # [win]
    - EIGEN3_INCLUDE_DIR={{ environ['PREFIX'] }}\\Library\\include\\eigen3  # [win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools >=64.0.0
    - setuptools-scm >=8.0.0
    - pybind11 >=2.10.0
    - wheel
    - pip
    - eigen
    - libboost-python-devel
  run:
    - python
    - numpy >=1.14
    - matplotlib >=3.0
    - networkx >=3.0
    - pydot >=3.0

test:
  imports:
    - pyvinecopulib
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://vinecopulib.github.io/pyvinecopulib
  summary: A python interface to vinecopulib
  description: |
    pyvinecopulib is the python interface to vinecopulib, a header-only C++
    library for vine copula models based on Eigen. It provides high-performance
    implementations of the core features of the popular VineCopula R library, in
    particular inference algorithms for both vine copula and bivariate copula models. 
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://vinecopulib.github.io/pyvinecopulib/
  dev_url: https://github.com/vinecopulib/pyvinecopulib

extra:
  recipe-maintainers:
    - tvatter
