{% set name = "pyvinecopulib" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyvinecopulib-{{ version }}.tar.gz
  sha256: 00cb8a6a54d35c732c5051be2624dba91672077fdcf7a44f39116fffd11adbc8

build:
  skip: true  # [py<38]
  script_env:
    - CMAKE_ARGS=-DBoost_INCLUDE_DIR={{ environ['PREFIX'] }}/include -DEIGEN3_INCLUDE_DIR={{ environ['PREFIX'] }}/include/eigen3  # [unix]
    - CMAKE_ARGS=-DBoost_INCLUDE_DIR={{ environ['PREFIX'] }}\\Library\\include -DEIGEN3_INCLUDE_DIR={{ environ['PREFIX'] }}\\Library\\include\\eigen3  # [win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - python
    - scikit-build-core >=0.4.3
    - nanobind >=1.3.2
    - wheel
    - pip
    - cmake
    - make
    - eigen
    - libboost-python-devel
  run:
    - python
    - numpy >=1.14
    - matplotlib >=3.0
    - networkx >=3.0
    - pydot >=3.0

test:
  imports:
    - pyvinecopulib
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://vinecopulib.github.io/pyvinecopulib
  summary: A python interface to vinecopulib
  description: |
    pyvinecopulib is the python interface to vinecopulib, a header-only C++
    library for vine copula models based on Eigen. It provides high-performance
    implementations of the core features of the popular VineCopula R library, in
    particular inference algorithms for both vine copula and bivariate copula models. 
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://vinecopulib.github.io/pyvinecopulib/
  dev_url: https://github.com/vinecopulib/pyvinecopulib

extra:
  recipe-maintainers:
    - tvatter
